name: Build Kernel

on:
  push:
    branches:
      - coloros12.1

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kernel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "CC_BIN=${{ github.workspace }}/kernel/clang11" >> $GITHUB_ENV
          echo "CLANG_PREBUILT_BIN=${{ github.workspace }}/kernel/clang11/bin" >> $GITHUB_ENV
          echo "LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_A=${{ github.workspace }}/kernel/clang11/aarch64-linux-android/bin" >> $GITHUB_ENV
          echo "LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_B=${{ github.workspace }}/kernel/clang11/arm-linux-androideabi-4.9/bin" >> $GITHUB_ENV
          echo "STOP_SHIP_TRACEPRINTK=1" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${{ github.workspace }}/kernel/clang11/lib64:\$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "${{ github.workspace }}/kernel/clang11/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/kernel/clang11/aarch64-linux-android/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/kernel/clang11/arm-linux-androideabi-4.9/bin" >> $GITHUB_PATH

      - name: Build kernel
        run: |
          make -j$(nproc --all) \
            O=out \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            ARCH=arm64 \
            BRANCH=android-4.14 \
            CC=clang \
            LD=ld.lld \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-androidkernel- \
            CROSS_COMPILE_COMPAT=arm-linux-androidkernel- \
            CROSS_COMPILE32=arm-linux-androidkernel- \
            CROSS_COMPILE_ARM32=arm-linux-androidkernel- \
            k6893v1_64_defconfig

          make -j$(nproc --all) \
            O=out \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            ARCH=arm64 \
            BRANCH=android-4.14 \
            CC=clang \
            LD=ld.lld \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-androidkernel- \
            CROSS_COMPILE_COMPAT=arm-linux-androidkernel- \
            CROSS_COMPILE32=arm-linux-androidkernel- \
            CROSS_COMPILE_ARM32=arm-linux-androidkernel-
