name: Kernel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'

      - name: Set up Clang
        run: |
          export CLANG_VERSION=clang-r383902
          export CLANG_URL=https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-release/${CLANG_VERSION}.tar.gz
          wget $CLANG_URL -O clang.tar.gz
          tar -xvzf clang.tar.gz -C clang11
          export CC_BIN=$(pwd)/clang11
          export CLANG_PREBUILT_BIN=$CC_BIN/bin
          export LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_A=$CC_BIN/aarch64-linux-android/bin
          export LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_B=$CC_BIN/arm-linux-androideabi-4.9/bin
          export PATH=$CLANG_PREBUILT_BIN:$LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_A:$LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_B:$PATH

      - name: Build Kernel
        run: |
          export kk="-j$(nproc --all) O=out ARCH=arm64 BRANCH=android-4.14 CC=clang LD=ld.lld CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-androidkernel- CROSS_COMPILE_COMPAT=arm-linux-androidkernel- CROSS_COMPILE32=arm-linux-androidkernel- CROSS_COMPILE_ARM32=arm-linux-androidkernel-"
          make $kk k6893v1_64_defconfig
          make $kk

      - name: Upload zImage or Image.gz
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: out/arch/arm64/boot/
